name: Publish extension

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21.x

      - name: Build webview
        run: cd webview && npm install && npm run build

      - name: Build extension
        run: cd extension && npm install && npm run build

      - name: Copy README so it gets published
        run: cp README.md extension

      - name: Copy LICENSE so it gets published
        run: cp LICENSE.md extension

      - name: Publish to Visual Studio Marketplace
        run: cd extension && npm run publish
        env:
          VSCE_PAT: ${{ secrets.VS_MARKETPLACE_TOKEN }}